// Code generated by goctl. DO NOT EDIT!
// Source: wallet.proto

package server

import (
	"context"

	"go-zero-rpctest/wallet/internal/logic"
	"go-zero-rpctest/wallet/internal/svc"
	"go-zero-rpctest/wallet/pb"
)

type WalletServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedWalletServer
}

func NewWalletServer(svcCtx *svc.ServiceContext) *WalletServer {
	return &WalletServer{
		svcCtx: svcCtx,
	}
}

func (s *WalletServer) GetCoinInfo(ctx context.Context, in *pb.CoinIdRequest) (*pb.WalletResponse, error) {
	l := logic.NewGetCoinInfoLogic(ctx, s.svcCtx)
	return l.GetCoinInfo(in)
}
