// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-zero-rpctest/user-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/profile",
				Handler: userInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: registerHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/test/middleware",
					Handler: userMiddlewareHandler(serverCtx),
				},
			}...,
		),
	)
}
